# Generated by Django 6.0 on 2025-12-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom d'affichage (ex: Gemini Pro Dev)", max_length=100)),
                ('provider', models.CharField(choices=[('mock', 'Mock (Simulation)'), ('google', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('mistral', 'Mistral AI'), ('perplexity', 'Perplexity')], default='mock', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='Clé API (laisser vide pour Mock)', max_length=255)),
                ('model_name', models.CharField(blank=True, help_text='Nom technique du modèle (ex: gemini-1.5-pro, gpt-4)', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='default_model',
            field=models.ForeignKey(blank=True, help_text='Modèle par défaut pour ce prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='core.aimodel'),
        ),
    ]
