# Generated by Django 6.0 on 2025-12-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aimodel_prompt_default_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', "En cours d'analyse"), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', max_length=20),
        ),
    ]
