# Generated by Django 6.0 on 2025-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_error_message_page_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
