# Generated by Django 6.0 on 2025-12-14 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du thème (ex: Énergie, Climat)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du thème')),
            ],
        ),
        migrations.RemoveField(
            model_name='argument',
            name='stance',
        ),
        migrations.AddField(
            model_name='textblock',
            name='hypostasis',
            field=models.CharField(blank=True, choices=[('classification', 'classification'), ('aporie', 'aporie'), ('approximation', 'approximation'), ('paradoxe', 'paradoxe'), ('formalisme', 'formalisme'), ('événement', 'événement'), ('variation', 'variation'), ('dimension', 'dimension'), ('mode', 'mode'), ('croyance', 'croyance'), ('invariant', 'invariant'), ('valeur', 'valeur'), ('structure', 'structure'), ('axiome', 'axiome'), ('conjecture', 'conjecture'), ('paradigme', 'paradigme'), ('objet', 'objet'), ('principe', 'principe'), ('domaine', 'domaine'), ('loi', 'loi'), ('phénomène', 'phénomène'), ('variable', 'variable'), ('variance', 'variance'), ('indice', 'indice'), ('donnée', 'donnée'), ('méthode', 'méthode'), ('définition', 'définition'), ('hypothèse', 'hypothèse'), ('problème', 'problème'), ('théorie', 'théorie')], help_text='Typologie conceptuelle (ex: classification, axiome, théorie…)', max_length=20, null=True, verbose_name='Hypostase'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='modes',
            field=models.CharField(blank=True, choices=[('IN', 'Initié'), ('DC', 'Discuté'), ('DP', 'Disputé'), ('CT', 'controversé'), ('CS', 'consensuel')], help_text='Statut argumentatif du contenu (ex: discuté, consensuel)', max_length=20, null=True, verbose_name='Mode de débat'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='significant_extract',
            field=models.TextField(blank=True, help_text='Extrait représentatif et concis du bloc', null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Modèle activé pour sélection'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock (Simulation)'), ('google', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('mistral', 'Mistral AI'), ('perplexity', 'Perplexity')], default='mock', help_text='Fournisseur du modèle', max_length=50),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='temperature',
            field=models.FloatField(default=0.7, help_text="Température d'échantillonnage du LLM"),
        ),
        migrations.AlterField(
            model_name='argument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Horodatage de création'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='end_offset',
            field=models.IntegerField(help_text='Offset de fin dans le nœud ciblé (sélecteur)'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='page',
            field=models.ForeignKey(help_text='Page source de l’argument', on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='core.page'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='selector',
            field=models.CharField(help_text='Sélecteur CSS du passage (doublon de sécurité si `text_block` est nul)', max_length=500),
        ),
        migrations.AlterField(
            model_name='argument',
            name='start_offset',
            field=models.IntegerField(help_text='Offset de départ dans le nœud ciblé (sélecteur)'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='summary',
            field=models.TextField(help_text='Résumé de l’argument (généré par IA ou édité)'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='text_block',
            field=models.ForeignKey(blank=True, help_text='Bloc d’origine si l’argument est ancré sur un passage précis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arguments', to='core.textblock'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='text_original',
            field=models.TextField(help_text='Texte source sur lequel l’argument se base'),
        ),
        migrations.AlterField(
            model_name='argument',
            name='user_edited',
            field=models.BooleanField(default=False, help_text='Coché si un humain a modifié l’argument'),
        ),
        migrations.AlterField(
            model_name='argumentcomment',
            name='argument',
            field=models.ForeignKey(help_text='Argument commenté', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.argument'),
        ),
        migrations.AlterField(
            model_name='argumentcomment',
            name='author',
            field=models.ForeignKey(help_text='Auteur du commentaire', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='argumentcomment',
            name='comment',
            field=models.TextField(help_text='Contenu du commentaire'),
        ),
        migrations.AlterField(
            model_name='argumentcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Horodatage de création'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_hash',
            field=models.CharField(blank=True, help_text='SHA256 hex du `text_readability`', max_length=64),
        ),
        migrations.AlterField(
            model_name='page',
            name='error_message',
            field=models.TextField(blank=True, help_text="Message d'erreur éventuel lors de l'analyse", null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_original',
            field=models.TextField(help_text='HTML original complet (immuable après création)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='html_readability',
            field=models.TextField(help_text="HTML simplifié (Readability) pour l'analyse"),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', "En cours d'analyse"), ('completed', 'Terminé'), ('error', 'Erreur')], default='pending', help_text='Statut de la dernière analyse', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_readability',
            field=models.TextField(help_text="Texte brut extrait de Readability (base de l'analyse)"),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, help_text='Titre optionnel détecté ou saisi', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(help_text='URL canonique de la page analysée', unique=True),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Horodatage de création'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='default_model',
            field=models.ForeignKey(blank=True, help_text='Modèle par défaut utilisé pour ce prompt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='core.aimodel'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='description',
            field=models.TextField(blank=True, help_text='Description / intention du prompt'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(help_text='Nom lisible du prompt composable', max_length=200),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='end_offset',
            field=models.IntegerField(help_text='Offset de fin dans le `textContent` du nœud'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='page',
            field=models.ForeignKey(help_text='Page à laquelle appartient ce bloc', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.page'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='selector',
            field=models.CharField(help_text='Sélecteur CSS (querySelector) qui pointe vers le nœud', max_length=500),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='start_offset',
            field=models.IntegerField(help_text='Offset de départ dans le `textContent` du nœud'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='text',
            field=models.TextField(help_text='Texte brut du bloc (extrait côté extension)'),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='content',
            field=models.TextField(help_text='Contenu texte de la brique (sera concaténé)'),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='name',
            field=models.CharField(help_text='Nom lisible de la brique', max_length=200),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordre d’assemblage dans le prompt'),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='prompt',
            field=models.ForeignKey(help_text='Prompt auquel appartient cette brique', on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='core.prompt'),
        ),
        migrations.AlterField(
            model_name='textinput',
            name='role',
            field=models.CharField(choices=[('context', 'Contexte sémantique'), ('instruction', 'Instruction'), ('format', 'Format de sortie')], help_text='Rôle de la brique dans le prompt', max_length=50),
        ),
        migrations.CreateModel(
            name='Reformulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('style', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reformulations', to='core.textblock')),
            ],
        ),
        migrations.AddField(
            model_name='textblock',
            name='themes',
            field=models.ManyToManyField(help_text='Thèmes associés à ce bloc', related_name='text_blocks', to='core.theme'),
        ),
    ]
