# Generated by Django 6.0 on 2025-12-14 13:41

from django.db import migrations

def create_textblocks_from_arguments(apps, schema_editor):
    Argument = apps.get_model('core', 'Argument')
    TextBlock = apps.get_model('core', 'TextBlock')

    for argument in Argument.objects.all():
        if argument.text_block:
            continue
            
        # Create TextBlock
        text_block = TextBlock.objects.create(
            page=argument.page,
            selector=argument.selector,
            start_offset=argument.start_offset,
            end_offset=argument.end_offset,
            text=argument.text_original,
            # Initialize other fields as empty/null
        )
        
        # Link Argument to TextBlock
        argument.text_block = text_block
        argument.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_theme_remove_argument_stance_textblock_hypostasis_and_more'),
    ]

    operations = [
        migrations.RunPython(create_textblocks_from_arguments),
    ]
