# Generated by Django 6.0 on 2025-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_migrate_arguments_to_textblocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='modes',
            field=models.CharField(choices=[('IN', 'Initié'), ('DC', 'Discuté'), ('DP', 'Disputé'), ('CT', 'controversé'), ('CS', 'consensuel')], default='IN', help_text='Statut argumentatif du contenu (ex: discuté, consensuel)', max_length=20, verbose_name='Mode de débat'),
        ),
    ]
