# Generated by Django 6.0 on 2025-12-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_textblock_modes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypostasisTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='hypostasis',
        ),
        migrations.AlterField(
            model_name='textblock',
            name='modes',
            field=models.CharField(choices=[('IN', 'A initier'), ('DC', 'Discuté'), ('DP', 'Disputé'), ('CT', 'controversé'), ('CS', 'consensuel')], default='IN', help_text='Statut argumentatif du contenu (ex: discuté, consensuel)', max_length=20, verbose_name='Mode de débat'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='hypostases',
            field=models.ManyToManyField(blank=True, help_text='Typologies conceptuelles (ex: classification, axiome, théorie…)', related_name='text_blocks', to='core.hypostasistag', verbose_name='Hypostases'),
        ),
    ]
