# Generated by Django 6.0 on 2026-02-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aimodel_model_choice_alter_aimodel_model_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du dossier', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_choice',
            field=models.CharField(choices=[('gemini-2.5-pro', 'Gemini 2.5 Pro (Google)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash (Google)'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (Google)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (Google)'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite (Google)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google)'), ('gemini-1.0-pro', 'Gemini 1.0 Pro (Google)'), ('gpt-5.2', 'GPT-5.2 (OpenAI)'), ('gpt-5-mini', 'GPT-5 Mini (OpenAI)'), ('gpt-5-nano', 'GPT-5 Nano (OpenAI)'), ('gpt-4.1', 'GPT-4.1 (OpenAI)'), ('gpt-4.1-mini', 'GPT-4.1 Mini (OpenAI)'), ('gpt-4.1-nano', 'GPT-4.1 Nano (OpenAI)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-4-turbo', 'GPT-4 Turbo (OpenAI)'), ('gpt-4', 'GPT-4 (OpenAI)'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (OpenAI)'), ('mistral-large-latest', 'Mistral Large (Mistral)'), ('mistral-medium-latest', 'Mistral Medium (Mistral)'), ('mistral-small-latest', 'Mistral Small (Mistral)'), ('open-mistral-7b', 'Mistral 7B (Mistral)'), ('open-mixtral-8x7b', 'Mixtral 8x7B (Mistral)'), ('open-mixtral-8x22b', 'Mixtral 8x22B (Mistral)'), ('sonar', 'Sonar (Perplexity)'), ('sonar-pro', 'Sonar Pro (Perplexity)'), ('llama-3.1-sonar-large-128k-online', 'Llama 3.1 Sonar Large (Perplexity)'), ('claude-opus-4-6', 'Claude Opus 4.6 (Anthropic)'), ('claude-sonnet-4-5', 'Claude Sonnet 4.5 (Anthropic)'), ('claude-haiku-4-5', 'Claude Haiku 4.5 (Anthropic)'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet Legacy (Anthropic)'), ('claude-3-opus-20240229', 'Claude 3 Opus Legacy (Anthropic)'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet Legacy (Anthropic)'), ('claude-3-haiku-20240307', 'Claude 3 Haiku Legacy (Anthropic)'), ('kimi-k2.5', 'Kimi K2.5 (Moonshot AI)'), ('kimi-k1.5', 'Kimi K1.5 (Moonshot AI)'), ('kimi-k2', 'Kimi K2 (Moonshot AI)'), ('mock', 'Mock / Simulation')], default='mock', help_text='Modèle AI à utiliser (sélection unique qui détermine automatiquement le provider)', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Dossier de classement (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='core.dossier'),
        ),
    ]
