# Generated by Django 6.0 on 2026-02-12 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dossier_alter_aimodel_model_choice_page_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_active', models.BooleanField(default=False, help_text="Active ou desactive l'IA globalement / Globally enable or disable AI")),
                ('ai_model', models.ForeignKey(blank=True, help_text='Modele IA actuellement selectionne / Currently selected AI model', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodel')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
