# Generated by Django 6.0 on 2026-02-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='original_filename',
            field=models.CharField(blank=True, help_text="Nom du fichier original (uniquement pour source_type='file')", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='source_type',
            field=models.CharField(choices=[('web', 'Page web'), ('file', 'Fichier importé')], default='web', help_text='Type de source : page web ou fichier importé', max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, help_text='URL canonique de la page analysée (null pour les fichiers importés)', null=True),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('url__isnull', False)), fields=('url',), name='unique_url_si_presente'),
        ),
    ]
