# Generated by Django 6.0 on 2026-02-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_page_original_filename_page_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom d'affichage de la configuration de transcription", max_length=100)),
                ('provider', models.CharField(choices=[('voxtral', 'Voxtral (Mistral AI)'), ('mock', 'Mock (Simulation)')], default='mock', help_text='Fournisseur de transcription (Voxtral ou Mock)', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='Cle API Mistral (laisser vide pour Mock)', max_length=255)),
                ('model_name', models.CharField(default='mistral-small-latest', help_text='Nom technique du modele de transcription', max_length=100)),
                ('language', models.CharField(default='fr', help_text='Code langue pour la transcription (ex: fr, en)', max_length=10)),
                ('diarization_enabled', models.BooleanField(default=True, help_text='Activer la diarisation (identification des locuteurs)')),
                ('max_speakers', models.PositiveIntegerField(default=5, help_text='Nombre maximum de locuteurs a detecter')),
                ('is_active', models.BooleanField(default=True, help_text='Configuration active pour la transcription')),
            ],
            options={
                'verbose_name': 'Configuration de transcription',
                'verbose_name_plural': 'Configurations de transcription',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='source_type',
            field=models.CharField(choices=[('web', 'Page web'), ('file', 'Fichier importé'), ('audio', 'Audio transcrit')], default='web', help_text='Type de source : page web ou fichier importé', max_length=10),
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, help_text='ID de la tache Celery associee', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Termine'), ('error', 'Erreur')], default='pending', help_text='Statut actuel du job de transcription', max_length=20)),
                ('raw_result', models.JSONField(blank=True, help_text='Resultat brut de la transcription (segments JSON)', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'echec")),
                ('audio_filename', models.CharField(blank=True, help_text='Nom du fichier audio original', max_length=500)),
                ('processing_time_seconds', models.FloatField(blank=True, help_text='Duree de traitement en secondes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(help_text='Page associee a cette transcription', on_delete=django.db.models.deletion.CASCADE, related_name='transcription_jobs', to='core.page')),
                ('transcription_config', models.ForeignKey(blank=True, help_text='Configuration de transcription utilisee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.transcriptionconfig')),
            ],
            options={
                'verbose_name': 'Job de transcription',
                'verbose_name_plural': 'Jobs de transcription',
                'ordering': ['-created_at'],
            },
        ),
    ]
