# Generated by Django 6.0 on 2026-02-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transcriptionconfig_alter_page_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionconfig',
            name='model_choice',
            field=models.CharField(choices=[('voxtral-mini-latest', 'Voxtral Mini (Mistral AI)'), ('mistral-small-latest', 'Mistral Small (Mistral AI)'), ('mistral-large-latest', 'Mistral Large (Mistral AI)'), ('mock', 'Mock / Simulation')], default='mock', help_text='Modele de transcription (determine automatiquement le provider)', max_length=100),
        ),
        migrations.AlterField(
            model_name='transcriptionconfig',
            name='model_name',
            field=models.CharField(default='mock', help_text='[LEGACY] Nom technique - deduit automatiquement du modele choisi', max_length=100),
        ),
        migrations.AlterField(
            model_name='transcriptionconfig',
            name='provider',
            field=models.CharField(choices=[('voxtral', 'Voxtral (Mistral AI)'), ('mock', 'Mock (Simulation)')], default='mock', help_text='[LEGACY] Fournisseur - deduit automatiquement du modele choisi', max_length=50),
        ),
    ]
