# Generated by Django 6.0 on 2026-02-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transcription_model_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_choice',
            field=models.CharField(choices=[('gemini-2.5-pro', 'Gemini 2.5 Pro (Google)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash (Google)'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (Google)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (Google)'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite (Google)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-4-turbo', 'GPT-4 Turbo (OpenAI)'), ('gpt-4.1', 'GPT-4.1 (OpenAI)'), ('gpt-4.1-mini', 'GPT-4.1 Mini (OpenAI)'), ('mock', 'Mock / Simulation')], default='mock', help_text='Modèle AI à utiliser (sélection unique qui détermine automatiquement le provider)', max_length=100),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock (Simulation)'), ('google', 'Google Gemini'), ('openai', 'OpenAI GPT')], default='mock', help_text='[LEGACY] Fournisseur - déduit automatiquement du modèle choisi', max_length=50),
        ),
    ]
