# Generated by Django 6.0 on 2026-02-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_aimodel_model_choice_alter_aimodel_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(help_text="Prenom de l'auteur de la question / Author first name", max_length=100)),
                ('texte_question', models.TextField(help_text='Texte de la question / Question text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(help_text='Page a laquelle cette question se rapporte / Page this question relates to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.page')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(help_text="Prenom de l'auteur de la reponse / Author first name", max_length=100)),
                ('texte_reponse', models.TextField(help_text='Texte de la reponse / Answer text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(help_text='Question a laquelle cette reponse repond / Question this answer replies to', on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.question')),
            ],
            options={
                'verbose_name': 'Reponse',
                'verbose_name_plural': 'Reponses',
                'ordering': ['created_at'],
            },
        ),
    ]
