# Generated by Django 6.0 on 2026-02-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_question_reponsequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='transcription_raw',
            field=models.JSONField(blank=True, help_text='Segments JSON bruts de la transcription audio (immuable apres creation)', null=True),
        ),
    ]
