# Generated by Django 6.0 on 2026-02-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ajout_transcription_raw_sur_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, help_text='Page originale dont celle-ci est une restitution / Original page this is a restitution of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restitutions', to='core.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='version_label',
            field=models.CharField(blank=True, default='', help_text='Label descriptif de cette version / Descriptive label for this version', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='version_number',
            field=models.PositiveIntegerField(default=1, help_text='Numero de version (1 = original) / Version number (1 = original)'),
        ),
    ]
