# Generated by Django 6.0.2 on 2026-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_page_parent_page_page_version_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='source_file',
            field=models.FileField(blank=True, help_text='Fichier source original (audio, document ou JSON uploade)', null=True, upload_to='sources/'),
        ),
    ]
