# Generated by Django 6.0.2 on 2026-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_source_file_to_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='base_url',
            field=models.CharField(blank=True, default='', help_text='URL de base du serveur (utilise par Ollama, ex: http://localhost:11434)', max_length=500),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_choice',
            field=models.CharField(choices=[('gemini-2.5-pro', 'Gemini 2.5 Pro (Google)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash (Google)'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (Google)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (Google)'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite (Google)'), ('gemini-1.5-pro', 'Gemini 1.5 Pro (Google)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash (Google)'), ('gpt-4o', 'GPT-4o (OpenAI)'), ('gpt-4o-mini', 'GPT-4o Mini (OpenAI)'), ('gpt-4-turbo', 'GPT-4 Turbo (OpenAI)'), ('gpt-4.1', 'GPT-4.1 (OpenAI)'), ('gpt-4.1-mini', 'GPT-4.1 Mini (OpenAI)'), ('llama3', 'Llama 3 (Ollama)'), ('llama3.1', 'Llama 3.1 (Ollama)'), ('mistral', 'Mistral (Ollama)'), ('gemma2', 'Gemma 2 (Ollama)'), ('qwen2.5', 'Qwen 2.5 (Ollama)'), ('deepseek-r1', 'DeepSeek R1 (Ollama)'), ('phi3', 'Phi 3 (Ollama)'), ('claude-sonnet-4-20250514', 'Claude Sonnet 4 (Anthropic)'), ('claude-haiku-4-20250414', 'Claude Haiku 4 (Anthropic)'), ('mock', 'Mock / Simulation')], default='mock', help_text='Modèle AI à utiliser (sélection unique qui détermine automatiquement le provider)', max_length=100),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock (Simulation)'), ('google', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('ollama', 'Ollama (Local)'), ('anthropic', 'Anthropic Claude')], default='mock', help_text='[LEGACY] Fournisseur - déduit automatiquement du modèle choisi', max_length=50),
        ),
    ]
