# Generated by Django 6.0.2 on 2026-03-15 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_phase25_users_partage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dossierpartage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dossier',
            name='visibilite',
            field=models.CharField(choices=[('prive', 'Privé'), ('partage', 'Partagé'), ('public', 'Public')], default='prive', help_text='Niveau de visibilite du dossier / Folder visibility level', max_length=10),
        ),
        migrations.AlterField(
            model_name='dossierpartage',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text='Utilisateur cible du partage (null si partage par groupe)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_partages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupeUtilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du groupe / Group name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membres', models.ManyToManyField(blank=True, help_text='Membres du groupe / Group members', related_name='groupes_membre', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Proprietaire du groupe / Group owner', on_delete=django.db.models.deletion.CASCADE, related_name='groupes_possedes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Groupe d'utilisateurs",
                'verbose_name_plural': "Groupes d'utilisateurs",
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='dossierpartage',
            name='groupe',
            field=models.ForeignKey(blank=True, help_text='Groupe cible du partage (null si partage direct)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partages_dossier', to='core.groupeutilisateurs'),
        ),
        migrations.AddConstraint(
            model_name='dossierpartage',
            constraint=models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', False)), fields=('dossier', 'utilisateur'), name='unique_partage_dossier_utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='dossierpartage',
            constraint=models.UniqueConstraint(condition=models.Q(('groupe__isnull', False)), fields=('dossier', 'groupe'), name='unique_partage_dossier_groupe'),
        ),
        migrations.AddConstraint(
            model_name='dossierpartage',
            constraint=models.CheckConstraint(condition=models.Q(('groupe__isnull', True), ('utilisateur__isnull', True), _negated=True), name='partage_dossier_au_moins_un_cible'),
        ),
    ]
