# Generated by Django 6.0.2 on 2026-03-15 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_dossierpartage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(help_text='Dossier suivi / Followed folder', on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='core.dossier')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur qui suit le dossier / User following the folder', on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_suivis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi de dossier',
                'verbose_name_plural': 'Suivis de dossiers',
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'dossier'), name='unique_suivi_utilisateur_dossier')],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Adresse email du destinataire / Recipient email address', max_length=254)),
                ('token', models.CharField(help_text="Token unique d'acceptation (secrets.token_hex(32)) / Unique acceptance token", max_length=64, unique=True)),
                ('acceptee', models.BooleanField(default=False, help_text="True si l'invitation a ete acceptee / True if invitation was accepted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text="Date d'expiration de l'invitation (now + 7 jours) / Invitation expiry date")),
                ('dossier', models.ForeignKey(blank=True, help_text="Dossier cible de l'invitation (null si invitation groupe)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.dossier')),
                ('groupe', models.ForeignKey(blank=True, help_text="Groupe cible de l'invitation (null si invitation dossier)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.groupeutilisateurs')),
                ('invite_par', models.ForeignKey(help_text="Utilisateur qui a envoye l'invitation / User who sent the invitation", on_delete=django.db.models.deletion.CASCADE, related_name='invitations_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('dossier__isnull', True), ('groupe__isnull', True), _negated=True), name='invitation_au_moins_une_cible')],
            },
        ),
    ]
