# Generated by Django 6.0.2 on 2026-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dossiersuivi_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description courte du dossier (optionnel) / Short folder description (optional)', max_length=200),
        ),
    ]
