# Generated by Django 6.0.2 on 2026-03-18 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_dossier_description'),
        ('hypostasis_extractor', '0023_extractionjob_tokens_reels_analyseur_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_euros', models.DecimalField(decimal_places=2, default=0, help_text='Solde actuel en euros / Current balance in euros', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Utilisateur proprietaire du compte / Account owner', on_delete=django.db.models.deletion.CASCADE, related_name='compte_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compte de credits',
                'verbose_name_plural': 'Comptes de credits',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('RECHARGE', 'Recharge'), ('DEBIT_ANALYSE', 'Debit analyse'), ('AJUSTEMENT', 'Ajustement'), ('REMBOURSEMENT', 'Remboursement')], help_text='Type de transaction / Transaction type', max_length=20)),
                ('montant_euros', models.DecimalField(decimal_places=2, help_text='Montant en euros (positif=credit, negatif=debit) / Amount in euros', max_digits=10)),
                ('solde_apres_euros', models.DecimalField(decimal_places=2, help_text='Solde apres la transaction / Balance after transaction', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID du PaymentIntent Stripe (idempotence) / Stripe PaymentIntent ID', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description de la transaction / Transaction description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(help_text='Compte de credits associe / Associated credit account', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.creditaccount')),
                ('cree_par', models.ForeignKey(blank=True, help_text="Utilisateur a l'origine de la transaction / User who initiated", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_credits', to=settings.AUTH_USER_MODEL)),
                ('extraction_job', models.ForeignKey(blank=True, help_text="Job d'extraction associe au debit / Associated extraction job", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_credits', to='hypostasis_extractor.extractionjob')),
            ],
            options={
                'verbose_name': 'Transaction de credits',
                'verbose_name_plural': 'Transactions de credits',
                'ordering': ['-created_at'],
            },
        ),
    ]
