# Generated by Django 6.0.2 on 2026-03-20 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_credit_account_and_credit_transaction'),
        ('hypostasis_extractor', '0023_extractionjob_tokens_reels_analyseur_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_edit', models.CharField(choices=[('titre', 'Titre modifié'), ('contenu', 'Contenu modifié'), ('bloc_transcription', 'Bloc de transcription modifié'), ('locuteur', 'Locuteur renommé')], help_text="Type d'edition / Edit type", max_length=30)),
                ('description', models.CharField(help_text="Resume humain de l'edition / Human-readable edit summary", max_length=500)),
                ('donnees_avant', models.JSONField(default=dict, help_text="Etat avant l'edition / State before the edit")),
                ('donnees_apres', models.JSONField(default=dict, help_text="Etat apres l'edition / State after the edit")),
                ('page', models.ForeignKey(help_text="Page concernee par l'edition / Page affected by the edit", on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='core.page')),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur ayant fait l'edition / User who made the edit", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_edits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edition de page',
                'verbose_name_plural': 'Editions de pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_char_cible', models.PositiveIntegerField(help_text='Position de debut dans le texte cible / Start position in target text')),
                ('end_char_cible', models.PositiveIntegerField(help_text='Position de fin dans le texte cible / End position in target text')),
                ('start_char_source', models.PositiveIntegerField(blank=True, help_text='Position de debut dans le texte source / Start position in source text', null=True)),
                ('end_char_source', models.PositiveIntegerField(blank=True, help_text='Position de fin dans le texte source / End position in source text', null=True)),
                ('type_lien', models.CharField(choices=[('identique', 'Identique'), ('modifie', 'Modifié'), ('nouveau', 'Nouveau'), ('supprime', 'Supprimé')], help_text='Type de lien de provenance / Provenance link type', max_length=20)),
                ('justification', models.TextField(blank=True, help_text='Justification du lien / Justification for the link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commentaires_source', models.ManyToManyField(blank=True, help_text="Commentaires a l'origine du passage / Comments that originated the passage", related_name='source_links', to='hypostasis_extractor.commentaireextraction')),
                ('extraction_source', models.ForeignKey(blank=True, help_text="Extraction a l'origine du passage / Extraction that originated the passage", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_links', to='hypostasis_extractor.extractedentity')),
                ('page_cible', models.ForeignKey(help_text='Page contenant le passage cible / Page containing the target passage', on_delete=django.db.models.deletion.CASCADE, related_name='source_links_cible', to='core.page')),
                ('page_source', models.ForeignKey(blank=True, help_text='Page source du passage / Source page for the passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_links_source', to='core.page')),
            ],
            options={
                'verbose_name': 'Lien de provenance',
                'verbose_name_plural': 'Liens de provenance',
            },
        ),
    ]
