# Generated by Django 6.0.2 on 2026-03-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pageedit_sourcelink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageedit',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Edition de page', 'verbose_name_plural': 'Editions de pages'},
        ),
    ]
