# Generated by Django 6.0.2 on 2026-03-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_pageedit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='transcriptionconfig',
            name='api_key',
        ),
    ]
