# Generated by Django 6.0.2 on 2026-05-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_api_key_from_aimodel_and_transcriptionconfig'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dossiersuivi',
            name='unique_suivi_utilisateur_dossier',
        ),
        migrations.DeleteModel(
            name='DossierSuivi',
        ),
    ]
