# Generated by Django 6.0.2 on 2026-05-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_dossiersuivi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credittransaction',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='extraction_job',
        ),
        migrations.DeleteModel(
            name='CreditAccount',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
    ]
