# Generated by Django 6.0.2 on 2026-05-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_credit_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='notification_lue',
            field=models.BooleanField(default=False, help_text='Notification de fin lue par le proprietaire / End-of-task notification read by the owner'),
        ),
    ]
