# Generated by Django 6.0.2 on 2026-05-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_marquer_notifications_existantes_lues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reformulation',
        ),
    ]
