# Generated by Django 6.0.2 on 2026-05-02 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_a7_retrait_modele_reformulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, help_text='Page parente — celle-ci est une version (synthese) de la parente / Parent page — this is a version (synthesis) of parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions_enfants', to='core.page'),
        ),
    ]
