# Generated by Django 6.0.2 on 2026-08-05 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_a7_renommer_related_name_versions_enfants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_stable', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Notre identifiant. Ne change jamais, meme apres scission ou fusion — c'est ce a quoi toute ancre se refere.", unique=True)),
                ('reference_docling', models.CharField(blank=True, help_text="Le self_ref d'origine, ex '#/texts/4'. Indicatif seulement, jamais utilise comme cle.", max_length=64)),
                ('ordre', models.PositiveIntegerField(help_text="Position dans le document, 0, 1, 2, 3... Renumerote librement a chaque scission/fusion/ajout : rien d'autre ne depend de sa valeur numerique que le tri.")),
                ('label', models.CharField(help_text='Label Docling : text, section_header, title, list_item, table, formula, code...', max_length=32)),
                ('texte', models.TextField(help_text="Le texte de cet element. C'est ici qu'on ancre.")),
                ('empreinte_contenu', models.CharField(db_index=True, help_text="SHA256 du texte normalise (espaces ecrases, minuscules). Utilise par le moteur d'ajout par re-ingestion pour reconnaitre un element inchange.", max_length=64)),
                ('chemin_de_section', models.JSONField(default=list, help_text="Titres parents au moment de l'ingestion, ex ['Introduction', '1) Le calcul des IA']. Instantane, pas re-derive automatiquement apres une scission de titre.")),
                ('provenance', models.JSONField(default=dict, help_text='Provenance physique, selon la source. PDF -> {page_no, boites: [{l,t,r,b,coord_origin}, ...]} (LISTE de boites : un paragraphe a cheval sur deux pages ou deux colonnes produit plusieurs entrees). audio -> {start_time, end_time, voice}. md/html/txt -> {}')),
                ('etat', models.CharField(choices=[('libre', 'Libre — aucune extraction'), ('analyse', 'Analysé — extractions sans commentaire'), ('debattu', 'Débattu — des commentaires sont attachés')], default='libre', help_text='Recalcule par signal. Ne jamais assigner a la main.', max_length=16)),
                ('masque', models.BooleanField(default=False, help_text='Element retire du contenu utile sans etre supprime. Cas reel : la transcription audio invente un segment (bruit, musique, doublon). Reversible, trace dans ElementOperation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Element de document',
                'verbose_name_plural': 'Elements de document',
                'ordering': ['page', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ElementOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('scission', 'Élément scindé'), ('fusion', 'Éléments fusionnés'), ('masquage', 'Élément masqué'), ('demasquage', 'Élément démasqué')], help_text="Type d'operation de structure / Structural operation type", max_length=16)),
                ('justification', models.TextField(blank=True, help_text='Pourquoi cette operation a ete faite / Why this operation was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operation sur un element',
                'verbose_name_plural': 'Operations sur les elements',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
