# Generated by Django 6.0.2 on 2026-08-05 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_elementdocument_elementoperation'),
        ('hypostasis_extractor', '0031_ancrageextraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelink',
            name='ancrage_source',
            field=models.ForeignKey(blank=True, help_text="La portion d'extraction precise qui a alimente ce passage de synthese / The precise extraction portion that fed this passage", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_de_provenance', to='hypostasis_extractor.ancrageextraction'),
        ),
        migrations.AddField(
            model_name='elementdocument',
            name='element_parent',
            field=models.ForeignKey(blank=True, help_text="Si cet element vient d'une scission ou d'une fusion, l'element (ou l'un des elements) d'origine. Indicatif, l'historique complet est dans ElementOperation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements_issus_d_une_operation', to='core.elementdocument'),
        ),
        migrations.AddField(
            model_name='elementdocument',
            name='page',
            field=models.ForeignKey(help_text='Page a laquelle cet element appartient / Page this element belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='core.page', verbose_name='Page qui contient cet element'),
        ),
        migrations.AddField(
            model_name='elementoperation',
            name='element',
            field=models.ForeignKey(help_text="Element concerne par l'operation / Element affected by the operation", on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.elementdocument'),
        ),
        migrations.AddField(
            model_name='elementoperation',
            name='user',
            field=models.ForeignKey(blank=True, help_text="Utilisateur ayant fait l'operation / User who performed the operation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_sur_elements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='elementdocument',
            constraint=models.UniqueConstraint(fields=('page', 'ordre'), name='unicite_ordre_dans_la_page'),
        ),
    ]
