# Generated by Django 6.0.2 on 2026-08-05 12:08

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_sourcelink_ancrage_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='elementdocument',
            name='unicite_ordre_dans_la_page',
        ),
        migrations.AddConstraint(
            model_name='elementdocument',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('page', 'ordre'), name='unicite_ordre_dans_la_page'),
        ),
    ]
