# Generated by Django 6.0.2 on 2026-08-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_journal_operations_rattache_a_la_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementdocument',
            name='element_parent',
        ),
    ]
