# Generated by Django 6.0.2 on 2026-08-08 14:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_simplification_element_parent_et_etats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppartenanceDossierBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integre_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('epingle', models.BooleanField(default=False)),
                ('ordre_manuel', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Appartenance carnet-base',
                'verbose_name_plural': 'Appartenances carnet-base',
                'ordering': ['base', '-epingle', 'ordre_manuel', '-integre_le'],
            },
        ),
        migrations.CreateModel(
            name='AppartenancePageDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integree_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('epinglee', models.BooleanField(default=False, help_text='Remonte en tete du carnet, avant le tri normal')),
                ('ordre_manuel', models.PositiveIntegerField(default=0, help_text="Ordre de curation. 0 = pas d'ordre impose, on retombe sur le tri chronologique. Sert a donner un ordre NARRATIF : les temps d'une deliberation.")),
            ],
            options={
                'verbose_name': 'Appartenance note-carnet',
                'verbose_name_plural': 'Appartenances note-carnet',
                'ordering': ['dossier', '-epinglee', 'ordre_manuel', '-integree_le'],
            },
        ),
        migrations.CreateModel(
            name='BaseDeConnaissances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la base de connaissances / Knowledge base name', max_length=200)),
                ('slug', models.SlugField(help_text="Identifiant d'URL, ex 'reseau-tiers-lieux-occitanie'.", max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('visibilite', models.CharField(choices=[('prive', 'Privé'), ('partage', 'Partagé'), ('public', 'Public')], default='prive', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Base de connaissances',
                'verbose_name_plural': 'Bases de connaissances',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(blank=True, default='', max_length=7)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categorie de base',
                'verbose_name_plural': 'Categories de base',
                'ordering': ['liste', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CategorieDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(blank=True, default='', help_text="Hex optionnel, ex '#E69F00'. Vide = palette Wong par defaut.", max_length=7)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categorie de carnet',
                'verbose_name_plural': 'Categories de carnet',
                'ordering': ['liste', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ListeDeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Liste de categories',
                'verbose_name_plural': 'Listes de categories',
                'ordering': ['dossier', 'base', 'ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='role_special',
            field=models.CharField(blank=True, choices=[('a_ranger', 'À ranger'), ('mes_imports', 'Mes imports')], default='', help_text="Role technique ('a_ranger', 'mes_imports') ou vide. Un seul carnet par role et par proprietaire.", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(condition=models.Q(('role_special', ''), _negated=True), fields=('owner', 'role_special'), name='unicite_role_special_par_proprietaire'),
        ),
        migrations.AddField(
            model_name='appartenancedossierbase',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances_bases', to='core.dossier'),
        ),
        migrations.AddField(
            model_name='appartenancedossierbase',
            name='integre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_de_carnets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appartenancepagedossier',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances_pages', to='core.dossier'),
        ),
        migrations.AddField(
            model_name='appartenancepagedossier',
            name='integree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_de_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appartenancepagedossier',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances_dossiers', to='core.page'),
        ),
        migrations.AddField(
            model_name='basedeconnaissances',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bases_possedees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appartenancedossierbase',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenances_dossiers', to='core.basedeconnaissances'),
        ),
        migrations.AddField(
            model_name='appartenancedossierbase',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='appartenances', to='core.categoriebase'),
        ),
        migrations.AddField(
            model_name='appartenancepagedossier',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories de CE carnet appliquees a CETTE note. Validation applicative (phase B) : chaque categorie doit venir du meme carnet que cette appartenance.', related_name='appartenances', to='core.categoriedossier'),
        ),
        migrations.AddField(
            model_name='listedecategories',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listes_de_categories', to='core.basedeconnaissances'),
        ),
        migrations.AddField(
            model_name='listedecategories',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listes_de_categories', to='core.dossier'),
        ),
        migrations.AddField(
            model_name='categoriedossier',
            name='liste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_de_dossier', to='core.listedecategories'),
        ),
        migrations.AddField(
            model_name='categoriebase',
            name='liste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_de_base', to='core.listedecategories'),
        ),
        migrations.AddConstraint(
            model_name='appartenancedossierbase',
            constraint=models.UniqueConstraint(fields=('dossier', 'base'), name='unicite_dossier_dans_une_base'),
        ),
        migrations.AddConstraint(
            model_name='appartenancepagedossier',
            constraint=models.UniqueConstraint(fields=('page', 'dossier'), name='unicite_page_dans_un_dossier'),
        ),
        migrations.AddConstraint(
            model_name='listedecategories',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('base__isnull', True), ('dossier__isnull', False)), models.Q(('base__isnull', False), ('dossier__isnull', True)), _connector='OR'), name='liste_appartient_a_un_seul_contenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriedossier',
            constraint=models.UniqueConstraint(fields=('liste', 'nom'), name='unicite_nom_dans_la_liste'),
        ),
        migrations.AddConstraint(
            model_name='categoriebase',
            constraint=models.UniqueConstraint(fields=('liste', 'nom'), name='unicite_nom_dans_la_liste_de_base'),
        ),
    ]
