# Generated by Django 6.0.2 on 2026-08-08 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_estampiller_les_dossiers_speciaux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dossier',
            name='unicite_role_special_par_proprietaire',
        ),
        migrations.AddConstraint(
            model_name='dossier',
            constraint=models.UniqueConstraint(condition=models.Q(('role_special', ''), _negated=True), fields=('owner', 'role_special'), name='unicite_role_special_par_proprietaire', nulls_distinct=False),
        ),
    ]
