# Generated by Django 6.0.2 on 2026-08-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_dossier_unicite_role_special_par_proprietaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='guide_de_redaction',
            field=models.TextField(blank=True, default='', help_text='Conseils de redaction propres a ce carnet, montres aux contributeurs. Vide = pas de guide.'),
        ),
    ]
