# Generated by Django 6.0.2 on 2026-08-08 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_dossier_guide_de_redaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriedossier',
            name='couleur',
            field=models.CharField(blank=True, default='', help_text="Hex optionnel, ex '#E69F00'. Vide = palette Wong par defaut.", max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', message='Couleur au format #RRGGBB / #RRGGBB hex color')]),
        ),
    ]
