# Generated by Django 6.0.2 on 2026-08-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_categoriedossier_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='type_de_note',
            field=models.CharField(choices=[('note', 'Note'), ('wiki', 'Wiki'), ('synthese', 'Synthèse dirigée')], db_index=True, default='note', help_text="Ce que cette note est. Une synthese ou un wiki n'est JAMAIS source d'une autre synthese — voir core/services/synthese.py. / A synthesis is never a source for another synthesis.", max_length=10),
        ),
    ]
