# Generated by Django 6.0.2 on 2026-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_typer_les_syntheses_existantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelink',
            name='etat_de_la_source',
            field=models.CharField(choices=[('presente', 'Présente'), ('supprimee', 'Source supprimée'), ('detachee', 'Ancre détachée')], db_index=True, default='presente', help_text="Bascule par signal a la suppression de la source, ou par la reconciliation quand l'ancre se detache.", max_length=10),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='etat_de_verification',
            field=models.CharField(choices=[('non_verifie', 'Non vérifié'), ('verifie', 'Vérifié'), ('faible', 'Faible'), ('non_source', 'Non sourcé')], db_index=True, default='non_verifie', help_text='Verdict du controle de fidelite, par paire (affirmation, source).', max_length=12),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='ordre_dans_la_section',
            field=models.PositiveSmallIntegerField(default=0, help_text='Position de la citation dans sa section.'),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='section',
            field=models.CharField(blank=True, default='', help_text='Titre exact de la section citante. Sert aux operations de mise a jour (§ 6) et a la navigation.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sourcelink',
            name='type_lien',
            field=models.CharField(choices=[('identique', 'Identique'), ('modifie', 'Modifié'), ('nouveau', 'Nouveau'), ('supprime', 'Supprimé'), ('cite', 'Cite')], help_text='Type de lien de provenance / Provenance link type', max_length=20),
        ),
    ]
