# Generated by Django 6.0.2 on 2026-08-09 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_sourcelink_etat_de_la_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseDirigee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produite_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('axe_de_direction', models.ForeignKey(blank=True, help_text="L'axe qui a dirige la synthese, s'il y en a un.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheses_dirigees', to='core.listedecategories')),
                ('categorie_de_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheses_dirigees', to='core.categoriedossier')),
                ('dossier', models.ForeignKey(blank=True, help_text="Le carnet sur lequel la synthese a ete produite. NULL si le carnet a ete supprime depuis, ou si la demande venait d'une note hors carnet.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheses_dirigees', to='core.dossier')),
                ('notes_du_perimetre', models.ManyToManyField(help_text='Les notes effectivement dans le perimetre au moment de la production. Fige, jamais recalcule.', related_name='syntheses_qui_la_couvrent', to='core.page')),
                ('page', models.OneToOneField(help_text='La note qui porte la synthese. type_de_note = SYNTHESE.', on_delete=django.db.models.deletion.CASCADE, related_name='synthese_dirigee', to='core.page')),
                ('produite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheses_produites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Synthese dirigee',
                'verbose_name_plural': 'Syntheses dirigees',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.TextField(help_text="Ce sur quoi porte l'article, en une phrase. C'est une CONSIGNE DE REDACTION, pas un filtre — le perimetre est defini par categories_du_perimetre (§ 3.1.1).")),
                ('tours_de_mise_a_jour', models.PositiveIntegerField(default=1)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('categories_du_perimetre', models.ManyToManyField(blank=True, help_text="Les categories qui definissent le perimetre. Vide = tout le carnet. Les categories d'un meme axe se combinent en OU, les axes entre eux en ET (spec corpus § 8.2).", related_name='wikis', to='core.categoriedossier')),
                ('dossier', models.ForeignKey(help_text='Le carnet dont il synthetise les notes.', on_delete=django.db.models.deletion.CASCADE, related_name='wikis', to='core.dossier')),
                ('page', models.OneToOneField(help_text="La note qui porte l'article. type_de_note = WIKI.", on_delete=django.db.models.deletion.CASCADE, related_name='wiki', to='core.page')),
            ],
            options={
                'verbose_name': 'Wiki',
                'verbose_name_plural': 'Wikis',
            },
        ),
    ]
