# Generated by Django 6.0.2 on 2026-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_estampiller_les_syntheses_dirigees_existantes'),
        ('hypostasis_extractor', '0033_simplification_element_parent_et_etats'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesedirigee',
            name='extractions_du_perimetre',
            field=models.ManyToManyField(blank=True, help_text='Les extractions effectivement proposees au modele a la production. Fige. Vide + flag a False = synthese historique (perimetre inconnu, recalcul dynamique).', related_name='syntheses_qui_les_ont_vues', to='hypostasis_extractor.extractedentity'),
        ),
        migrations.AddField(
            model_name='synthesedirigee',
            name='perimetre_d_extractions_fige',
            field=models.BooleanField(default=False, help_text="True des que la production a fige la liste d'extractions ci-dessus — meme vide (analyseur sans extractions). False = historique d'avant la phase D."),
        ),
    ]
