# Generated by Django 6.0.2 on 2026-08-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_perimetre_d_extractions_fige'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelink',
            name='verifie_le',
            field=models.DateTimeField(blank=True, help_text='Quand le verdict a ete pose. NULL = jamais verifie.', null=True),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='verifie_par',
            field=models.CharField(blank=True, default='', help_text="Qui a pose le verdict : methode + modele + version (ex. « verbatim+nli-lot v1 — gpt-x ») ou l'humain qui conteste.", max_length=200),
        ),
        migrations.AlterField(
            model_name='sourcelink',
            name='etat_de_verification',
            field=models.CharField(choices=[('non_verifie', 'Non vérifié'), ('verifie', 'Vérifié'), ('faible', 'Faible'), ('non_source', 'Non sourcé'), ('conteste', 'Contesté'), ('source_debat', 'Sourcé par le débat')], db_index=True, default='non_verifie', help_text='Verdict du controle de fidelite, par paire (affirmation, source).', max_length=12),
        ),
    ]
