# Generated by Django 6.0.2 on 2026-08-09 21:49
"""
Le flag moteur d'une Page (SPEC-ancrage v2 § 9, branchement BR-A) :
schema + estampillage. Les pages qui portent deja des elements (moteur
ELEMENT teste hors production) passent ELEMENT ; TOUTES les autres
restent ANCIEN — aucune regression, aucune migration de force (§ 9.2).
Reversible : le champ disparait au rollback, rien d'autre ne bouge.
/ Page engine flag: schema + stamping; element-bearing pages become
ELEMENT, everything else stays ANCIEN.

LOCALISATION : core/migrations/0053_page_moteur.py
"""

from django.db import migrations, models


def estampiller_le_moteur(apps, schema_editor):
    """
    RIEN a estampiller — et c'est un choix, pas un oubli (§ 9.2) : les
    pages EXISTANTES restent ANCIEN, meme celles qui portent deja des
    elements (537 sur 541 en dev, ingeres par les phases de test du
    moteur : leurs elements DORMENT, le flux reel ne les lit pas).
    Basculer l'existant est une reconversion EXPLICITE (§ 9.5, decision
    D4), jamais un effet de migration. Le flag ELEMENT n'est pose que
    par les nouvelles ingestions (creer_les_elements_d_une_page).
    / Nothing stamped, deliberately: existing pages stay ANCIEN; the
    flag is only set by new ingestions.
    """
    total = apps.get_model("core", "Page").objects.count()
    print(
        f"\n[migration 0053] {total} page(s) existantes : toutes ANCIEN "
        f"(§ 9.2, aucune regression) — le flag vient des ingestions"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_provenance_du_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='moteur',
            field=models.CharField(choices=[('ancien', 'Ancien moteur (offsets)'), ('element', 'Moteur par élément')], db_index=True, default='ancien', help_text="Moteur d'ancrage : 'ancien' (offsets plats) ou 'element' (ElementDocument + portions). Les deux coexistent, aucune migration de force.", max_length=10),
        ),
        migrations.RunPython(
            estampiller_le_moteur,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
