# Generated by Django 6.0.2 on 2026-08-10 09:13

from django.db import migrations, models


def estampiller_les_pages_element(apps, schema_editor):
    """
    Les pages DEJA au moteur ELEMENT ont, par construction, une
    ingestion reussie (le flag `moteur` n'est pose que par
    creer_les_elements_d_une_page, en fin d'ingestion). On les
    estampille pour que la puce d'etat (U2) ne les prenne pas pour des
    pages « jamais demandees ». Les 537 pages ANCIEN aux elements
    dormants ne sont PAS touchees : leur ingestion de test n'est pas
    passee par le flux reel (§ 9.2).
    / ELEMENT pages by definition had a successful ingestion; dormant
    OLD pages are left untouched.
    """
    Page = apps.get_model("core", "Page")
    nombre = Page.objects.filter(moteur="element").update(
        ingestion_etat="reussie",
    )
    if nombre:
        print(f"\n[migration 0054] {nombre} page(s) ELEMENT estampillee(s) "
              "ingestion reussie")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_page_moteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ingestion_detail',
            field=models.TextField(blank=True, default='', help_text="Message FALC montre a l'utilisateur quand le decoupage a echoue. / Plain-words failure message."),
        ),
        migrations.AddField(
            model_name='page',
            name='ingestion_etat',
            field=models.CharField(blank=True, choices=[('en_attente', 'Découpage en attente'), ('en_cours', 'Découpage en cours'), ('reussie', 'Découpage réussi'), ('echouee', 'Découpage échoué')], default='', help_text="Etat du decoupage en elements (U2). Vide = jamais demande. Ecrit par la vue d'import (en_attente) et par la tache Docling (en_cours/reussie/echouee).", max_length=12),
        ),
        migrations.RunPython(
            estampiller_les_pages_element,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
