# Generated by Django 6.0.2 on 2026-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_page_ingestion_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ingestion_maj_le',
            field=models.DateTimeField(blank=True, help_text="Quand ingestion_etat a change pour la derniere fois (U2). Sert a detecter un etat actif FANTOME : un worker tue laisse 'en_cours' pour toujours ; au-dela d'un delai la relance est de nouveau permise. / When the state last changed; used to break a stale active state left by a dead worker.", null=True),
        ),
    ]
