# Generated by Django 6.0.2 on 2026-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_suppression_du_flag_moteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ingestion_notification_lue',
            field=models.BooleanField(default=False, help_text="La fin du decoupage en elements a-t-elle ete vue ? Symetrique du notification_lue des jobs d'analyse et de transcription (addendum du 11 aout 2026)."),
        ),
    ]
