# Generated by Django 6.0.2 on 2026-08-11 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_estampiller_les_ingestions_deja_vues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTacheLue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tache', models.CharField(choices=[('extraction', 'Extraction'), ('transcription', 'Transcription'), ('ingestion', 'Ingestion')], max_length=14)),
                ('tache_id', models.PositiveIntegerField(help_text="Pk de l'ExtractionJob, du TranscriptionJob ou de la Page (ingestion) concerne, selon type_tache.")),
                ('utilisateur', models.ForeignKey(help_text='Le destinataire qui a lu cette tache.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_taches_lues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'type_tache', 'tache_id'), name='unicite_notification_tache_lue_par_destinataire')],
            },
        ),
    ]
