# Generated by Django 6.0.2 on 2026-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_migrer_les_notifications_lues_par_destinataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='ingestion_notification_lue',
            field=models.BooleanField(default=False, help_text="La fin du decoupage en elements a-t-elle ete vue ? Symetrique du notification_lue des jobs d'analyse et de transcription (addendum du 11 aout 2026). MORT pour la decision depuis la correction 1 (11 aout, meme jour) : voir NotificationTacheLue, qui porte le drapeau PAR DESTINATAIRE. Champ laisse en base (pas de suppression de colonne) mais plus ecrit ni lu."),
        ),
        migrations.AlterField(
            model_name='transcriptionjob',
            name='notification_lue',
            field=models.BooleanField(default=False, help_text='Notification de fin lue par le proprietaire / End-of-task notification read by the owner. MORT pour la decision depuis la correction 1 (11 aout 2026) : voir NotificationTacheLue, qui porte le drapeau PAR DESTINATAIRE. Champ laisse en base mais plus ecrit ni lu.'),
        ),
    ]
