# Generated by Django 6.0.2 on 2026-08-12 07:08
#
# AJOUTE L'IMAGE DE COUVERTURE FACULTATIVE D'UNE BASE DE CONNAISSANCES.
# / Adds the optional cover image of a knowledge base.
#
# LOCALISATION : core/migrations/0062_ajouter_image_de_couverture_a_la_base.py
#
# Une seule operation, un seul champ. Le champ est `null=True, blank=True` :
# toute base deja creee le garde vide, et aucune donnee n'est reecrite —
# la migration est donc instantanee et reversible sans perte.
# `ImageField` exige Pillow au demarrage (check `fields.E210`) ; Pillow est
# present dans l'environnement, tire par docling-parse / pdfplumber /
# python-pptx. Il n'est PAS une dependance directe declaree de ce projet :
# a signaler au mainteneur plutot qu'a corriger ici.
# / One operation, one nullable field: no row is rewritten. ImageField
# needs Pillow, which is present but only as a transitive dependency.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_documenter_les_champs_de_notification_lue_morts'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedeconnaissances',
            name='image_de_couverture',
            field=models.ImageField(blank=True, help_text='Image de couverture facultative de la base. Vide : la carte affiche sa cote typographique.', null=True, upload_to='bases/couvertures/'),
        ),
    ]
