# Generated by Django 6.0.2 on 2026-08-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_ajouter_image_de_couverture_a_la_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcelink',
            name='etat_de_verification',
            field=models.CharField(choices=[('non_verifie', 'Non vérifié'), ('verifie', 'Vérifié'), ('faible', 'Faible'), ('introuvable', 'Citation introuvable'), ('non_source', 'Non sourcé'), ('conteste', 'Contesté'), ('source_debat', 'Sourcé par le débat')], db_index=True, default='non_verifie', help_text='Verdict du controle de fidelite, par paire (affirmation, source).', max_length=12),
        ),
    ]
