# Generated by Django 6.0.2 on 2026-08-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_verdict_citation_introuvable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_hash',
            field=models.CharField(blank=True, help_text="SHA256 du texte AU MOMENT DE L'IMPORT — empreinte de deduplication, jamais recalculee ensuite.", max_length=64),
        ),
        migrations.AlterField(
            model_name='page',
            name='text_readability',
            field=models.TextField(help_text="PROJECTION du texte des elements (moteur ELEMENT), reecrite a la reussite de l'ingestion. Ce n'est PLUS la verite du contenu d'une note : la verite, ce sont ses ElementDocument."),
        ),
    ]
