# Generated by Django 6.0.2 on 2026-08-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_doc_du_texte_plat_et_de_son_empreinte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleParRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('redacteur_d_article', "Rédacteur d'article"), ('juge_de_verification', 'Juge de vérification')], help_text="L'usage servi par ce modèle / The use this model serves", max_length=50, unique=True)),
                ('affecte_le', models.DateTimeField(auto_now=True, help_text='Date de la dernière affectation / Last assignment date')),
                ('modele', models.ForeignKey(help_text='Le modèle IA affecté / The assigned AI model', on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='core.aimodel')),
            ],
            options={
                'verbose_name': 'Modèle par rôle',
                'verbose_name_plural': 'Modèles par rôle',
                'ordering': ['role'],
            },
        ),
    ]
