# Generated by Django 6.0.2 on 2026-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_modeleparrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='variable_de_cle_api',
            field=models.CharField(blank=True, default='', help_text="Nom de la variable d'environnement qui porte la clé (ex: OPENROUTER_API_KEY). La clé elle-même n'est JAMAIS stockée en base.", max_length=100),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='base_url',
            field=models.CharField(blank=True, default='', help_text='URL de base du serveur (Ollama, OpenRouter, Mistral… ex: https://openrouter.ai/api/v1)', max_length=500),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('mock', 'Mock (Simulation)'), ('google', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('ollama', 'Ollama (Local)'), ('anthropic', 'Anthropic Claude'), ('compatible_openai', 'API compatible OpenAI (base_url)')], default='mock', help_text='[LEGACY] Fournisseur - déduit automatiquement du modèle choisi', max_length=50),
        ),
    ]
