# Generated by Django 6.0.2 on 2026-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_aimodel_model_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='temperature',
            field=models.FloatField(blank=True, default=0.7, help_text="Température d'échantillonnage du LLM. Vide = ne rien transmettre, le fournisseur décide (obligatoire pour les modèles de raisonnement d'OpenAI).", null=True),
        ),
    ]
