# Generated by Django 6.0.2 on 2026-08-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_aimodel_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='seuil_de_verification',
            field=models.FloatField(default=45.0, help_text="A partir de quel degre (0-100) un renvoi s'affiche « verifie ». Le changer ne rejuge rien."),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='provenance_du_verbatim',
            field=models.CharField(blank=True, choices=[('source', 'Dans la note source'), ('debat', 'Dans un commentaire du débat')], default='', help_text='Ou la citation exacte a ete retrouvee. Constate par le parcours deterministe, avant tout appel de juge.', max_length=10),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='score_de_verification',
            field=models.FloatField(blank=True, help_text="Dans quelle mesure la source etablit ce que l'affirmation avance, de 0 a 100. NULL = pas de degre (jamais juge, verdict sans juge, ou verdict anterieur au 18 aout 2026).", null=True),
        ),
    ]
