# Generated by Django 6.0.2 on 2026-08-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_score_de_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcelink',
            name='methode_du_second_avis',
            field=models.CharField(blank=True, default='', help_text='Qui a rendu le second avis : methode + severite + modele. La severite en fait partie : « large » et « strict » ne posent pas la meme question.', max_length=200),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='score_du_second_avis',
            field=models.FloatField(blank=True, help_text='Le degre rendu par le second juge, de 0 a 100. NULL = pas de second avis.', null=True),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='second_avis_rendu_le',
            field=models.DateTimeField(blank=True, help_text='Quand le second avis a ete rendu.', null=True),
        ),
        migrations.AddField(
            model_name='sourcelink',
            name='seuil_du_second_avis',
            field=models.FloatField(blank=True, help_text="Le seuil propre au second juge, fige au moment de l'avis. Jamais relu depuis la Configuration.", null=True),
        ),
    ]
