# Generated by Django 6.0.2 on 2026-08-19 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_second_avis_de_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisDeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(help_text="Qui a rendu l'avis : methode + cadrage + modele. Le cadrage en fait partie — la mesure du 18 aout a montre qu'il fait passer l'AUC de 0,54 a 0,92.", max_length=200)),
                ('score', models.FloatField(help_text="Le degre rendu, de 0 a 100, sur l'echelle de CE juge.")),
                ('seuil', models.FloatField(help_text="Le seuil propre a ce juge, fige au moment de l'avis. Jamais relu depuis la Configuration.")),
                ('rendu_le', models.DateTimeField(auto_now=True, help_text='Quand cet avis a ete rendu.')),
                ('lien', models.ForeignKey(help_text='La citation notee.', on_delete=django.db.models.deletion.CASCADE, related_name='avis_locaux', to='core.sourcelink')),
            ],
            options={
                'verbose_name': 'avis de vérification',
                'verbose_name_plural': 'avis de vérification',
                'indexes': [models.Index(fields=['lien', 'methode'], name='core_avisde_lien_id_2f370f_idx')],
                'constraints': [models.UniqueConstraint(fields=('lien', 'methode'), name='un_seul_avis_par_juge_et_par_citation')],
            },
        ),
    ]
