# Generated by Django 6.0.2 on 2026-08-19 14:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_avis_des_juges_locaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisdeverification',
            name='rendu_le',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Quand cet avis a ete rendu.'),
        ),
    ]
