# Generated by Django 6.0.2 on 2026-08-21 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_date_des_avis_non_reecrite'),
        ('hypostasis_extractor', '0035_prompt_de_synthese_sans_statuts_abolis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDeWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_tour', models.PositiveIntegerField(help_text='La valeur de Wiki.tours_de_mise_a_jour a ce tour.')),
                ('fait_le', models.DateTimeField(auto_now_add=True)),
                ('motif', models.CharField(choices=[('creation', 'Première rédaction'), ('maj_manuelle', 'Mise à jour acceptée par un humain'), ('maj_nocturne', 'Mise à jour automatique de la nuit'), ('reparation_de_titres', 'Réparation des niveaux de titre'), ('regeneration', "Régénération complète de l'article")], help_text="Pourquoi le corps de l'article a été écrit.", max_length=30)),
                ('depuis', models.DateTimeField(blank=True, help_text='La borne basse du comptage des nouveautés. NULL = pas de date de référence, donc aucune nouveauté comptée (jamais un compte inventé).', null=True)),
                ('extractions_nouvelles', models.PositiveIntegerField(default=0, help_text='Extractions apparues dans le périmètre depuis `depuis`, au moment du tour.')),
                ('commentaires_nouveaux', models.PositiveIntegerField(default=0, help_text='Commentaires apparus sur les extractions du périmètre depuis `depuis`, au moment du tour.')),
                ('texte_avant', models.TextField(blank=True, help_text="Le markdown de l'article avant ce tour.")),
                ('texte_apres', models.TextField(blank=True, help_text="Le markdown de l'article après ce tour.")),
                ('commentaires_declenchants', models.ManyToManyField(blank=True, help_text='Les commentaires posés depuis `depuis` sur des extractions du périmètre.', related_name='tours_de_wiki_declenches', to='hypostasis_extractor.commentaireextraction')),
                ('fait_par', models.ForeignKey(blank=True, help_text="L'humain qui a accepté les opérations. NULL = le moteur (passe de nuit).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_de_wiki', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text="La proposition d'où viennent les opérations.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_de_wiki', to='hypostasis_extractor.extractionjob')),
                ('notes_declenchantes', models.ManyToManyField(blank=True, help_text='Les notes entrées dans le périmètre depuis `depuis`.', related_name='tours_de_wiki_declenches', to='core.page')),
                ('wiki', models.ForeignKey(help_text='Le wiki dont ce tour raconte une modification.', on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.wiki')),
            ],
            options={
                'verbose_name': 'Tour de wiki',
                'verbose_name_plural': 'Tours de wiki',
                'ordering': ['-fait_le', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OperationDeWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(help_text='Sa place dans le lot proposé, à partir de 0.')),
                ('type_d_operation', models.CharField(choices=[('no_change', 'Aucun changement'), ('append_to_section', 'Ajout dans une section'), ('replace_section', "Remplacement d'une section"), ('insert_section', "Insertion d'une section")], help_text="Le type d'opération proposé par le modèle.", max_length=20)),
                ('section', models.CharField(blank=True, help_text='La section visée. Pour une insertion : le titre de la section créée.', max_length=200)),
                ('apres', models.CharField(blank=True, help_text='Insertion seulement : la section après laquelle insérer.', max_length=200)),
                ('contenu', models.TextField(blank=True, help_text="Ce que l'opération a écrit — CONSERVÉ même quand elle a été rejetée (§ 6.2).")),
                ('ancien_contenu', models.TextField(blank=True, help_text="Remplacement seulement : le corps de section qui a disparu (§ 6.4, le diff montre l'avant).")),
                ('appliquee', models.BooleanField(help_text='False = rejetée ; le motif dit pourquoi.')),
                ('motif_de_rejet', models.CharField(blank=True, help_text="Vide quand l'opération a été appliquée.", max_length=300)),
                ('extractions_citees', models.ManyToManyField(blank=True, help_text="Les extractions citées par le contenu, dérivées de ses marqueurs [[ext:N]] — jamais d'un champ parallèle (§ 4.4).", related_name='operations_de_wiki', to='hypostasis_extractor.extractedentity')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='core.tourdewiki')),
            ],
            options={
                'verbose_name': 'Opération de wiki',
                'verbose_name_plural': 'Opérations de wiki',
                'ordering': ['indice', 'pk'],
            },
        ),
    ]
