# Generated by Django 6.0.2 on 2026-08-21 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_tourdewiki_operationdewiki'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasseDeNuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancee_le', models.DateTimeField(auto_now_add=True)),
                ('terminee_le', models.DateTimeField(blank=True, help_text='NULL tant que la passe tourne.', null=True)),
                ('wikis_examines', models.PositiveIntegerField(default=0)),
                ('wikis_modifies', models.PositiveIntegerField(default=0)),
                ('wikis_en_erreur', models.PositiveIntegerField(default=0)),
                ('wikis_ecartes_par_le_maximum', models.PositiveIntegerField(default=0, help_text='Wikis laissés de côté par --maximum. Compté, jamais passé sous silence : une troncature muette se lirait comme une couverture complète.')),
            ],
            options={
                'verbose_name': 'Passe de nuit',
                'verbose_name_plural': 'Passes de nuit',
                'ordering': ['-lancee_le', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EnvoiDuRecapitulatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('couvre_depuis', models.DateTimeField(help_text='La borne basse de ce que le mail racontait.')),
                ('wikis_modifies', models.PositiveIntegerField(default=0)),
                ('wikis_avec_du_neuf', models.PositiveIntegerField(default=0)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recapitulatifs_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envoi du récapitulatif',
                'verbose_name_plural': 'Envois du récapitulatif',
                'ordering': ['-envoye_le', '-pk'],
            },
        ),
    ]
