# Generated by Django 6.0.2 on 2026-08-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_passedenuit_envoidurecapitulatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedenuit',
            name='wikis_termines',
            field=models.PositiveIntegerField(default=0, help_text='Combien ont rendu la main — succès et erreurs confondus. La passe se ferme quand ce compte rejoint wikis_examines.'),
        ),
        migrations.AlterField(
            model_name='passedenuit',
            name='wikis_examines',
            field=models.PositiveIntegerField(default=0, help_text='Combien de wikis ont été mis en file pour ce tour.'),
        ),
    ]
