# Generated by Django 6.0.2 on 2026-09-21 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_compteur_de_la_passe_de_nuit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasseDeNuit',
        ),
        migrations.AlterField(
            model_name='tourdewiki',
            name='fait_par',
            field=models.ForeignKey(blank=True, help_text="L'humain qui a accepté les opérations. NULL = aucun humain connu (ancienne passe de nuit, ou compte supprimé).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_de_wiki', to=settings.AUTH_USER_MODEL),
        ),
    ]
