# Generated by Django 6.0.2 on 2026-08-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_compteur_de_la_passe_de_nuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='envoidurecapitulatif',
            name='couvre_jusqu_a',
            field=models.DateTimeField(blank=True, help_text="L'instant où la matière a été calculée. C'est la borne basse du PROCHAIN envoi. NULL = envois d'avant ce champ.", null=True),
        ),
    ]
