# Generated by Django 6.0.2 on 2026-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_borne_haute_du_recapitulatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedenuit',
            name='verrou',
            field=models.BooleanField(default=True, editable=False, help_text="Toujours True. N'existe que pour porter la contrainte d'unicité qui interdit deux passes ouvertes en même temps."),
        ),
        migrations.AddConstraint(
            model_name='passedenuit',
            constraint=models.UniqueConstraint(condition=models.Q(('terminee_le__isnull', True)), fields=('verrou',), name='une_seule_passe_de_nuit_ouverte'),
        ),
    ]
