# Generated by Django 6.0.2 on 2026-08-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_une_seule_passe_ouverte'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdewiki',
            name='message_d_echec',
            field=models.TextField(blank=True, help_text="Ce qui a empêché ce tour d'aboutir. Vide quand il a abouti. Un échec se lit dans l'historique de l'article, pas seulement dans un journal de worker."),
        ),
        migrations.AlterField(
            model_name='tourdewiki',
            name='motif',
            field=models.CharField(choices=[('creation', 'Première rédaction'), ('maj_manuelle', 'Mise à jour acceptée par un humain'), ('maj_nocturne', 'Mise à jour automatique de la nuit'), ('reparation_de_titres', 'Réparation des niveaux de titre'), ('regeneration', "Régénération complète de l'article"), ('echec', 'Tentative échouée')], help_text="Pourquoi le corps de l'article a été écrit.", max_length=30),
        ),
    ]
