# Generated by Django 6.0.2 on 2026-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_un_echec_est_un_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdocument',
            name='provenance',
            field=models.JSONField(default=dict, help_text='Provenance physique, selon la source. PDF -> {page_no, boites: [{l,t,r,b,coord_origin}, ...]} (LISTE de boites : un paragraphe a cheval sur deux pages ou deux colonnes produit plusieurs entrees). audio -> {locuteur, debut, fin} (les cles ecrites par services/ingestion_audio.py, et lues par le rendu). md/html/txt -> {}'),
        ),
    ]
