# Generated by Django 6.0.2 on 2026-09-01 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_les_cles_de_provenance_audio'),
        ('hypostasis_extractor', '0040_les_deux_bascules_d_injection_disparaissent'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='analyseur_de_redaction',
            field=models.ForeignKey(blank=True, help_text="L'analyseur choisi à la création. Les mises à jour le suivent / The analyzer picked at creation; updates follow it", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wikis_rediges', to='hypostasis_extractor.analyseursyntaxique'),
        ),
    ]
