# Generated by Django 6.0 on 2026-02-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_hypostasistag_remove_textblock_hypostasis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'exemple", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('example_text', models.TextField(help_text="Texte source de l'exemple")),
                ('example_extractions', models.JSONField(help_text='Liste des extractions attendues [{extraction_class, extraction_text, attributes}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom descriptif du job', max_length=200)),
                ('prompt_description', models.TextField(help_text="Description de ce qu'on veut extraire (ex: 'Extraire les entites medicales')")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Termine'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, help_text='Resultat brut de LangExtract (JSON)', null=True)),
                ('entities_count', models.PositiveIntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(blank=True, help_text="Modele LLM utilise pour l'extraction", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodel')),
                ('page', models.ForeignKey(help_text="Page source pour l'extraction (utilise html_readability)", on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='core.page')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_class', models.CharField(help_text="Classe/categorie de l'entite extraite", max_length=100)),
                ('extraction_text', models.TextField(help_text='Texte exact extrait du document source')),
                ('start_char', models.PositiveIntegerField(help_text='Position de debut dans html_readability')),
                ('end_char', models.PositiveIntegerField(help_text='Position de fin dans html_readability')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text="Attributs additionnels extraits (ex: {emotion: 'wonder'})")),
                ('user_validated', models.BooleanField(default=False, help_text='Validee par un utilisateur humain')),
                ('user_notes', models.TextField(blank=True, help_text='Notes de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hypostasis_tag', models.ForeignKey(blank=True, help_text='Tag hypostasia associe (si mapping automatique reussi)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hypostasistag')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='hypostasis_extractor.extractionjob')),
            ],
            options={
                'ordering': ['start_char'],
            },
        ),
        migrations.CreateModel(
            name='JobExampleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypostasis_extractor.extractionexample')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hypostasis_extractor.extractionjob')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('job', 'example')},
            },
        ),
    ]
