# Generated by Django 6.0 on 2026-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedentity',
            name='end_char',
            field=models.PositiveIntegerField(help_text='Position de fin dans text_readability'),
        ),
        migrations.AlterField(
            model_name='extractedentity',
            name='start_char',
            field=models.PositiveIntegerField(help_text='Position de debut dans text_readability'),
        ),
    ]
