# Generated by Django 6.0 on 2026-02-10 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0002_alter_extractedentity_end_char_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseurSyntaxique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'analyseur", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description de l'analyseur")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyseurExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de l'exemple", max_length=200)),
                ('example_text', models.TextField(help_text="Texte source de l'exemple")),
                ('order', models.PositiveIntegerField(default=0)),
                ('analyseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='hypostasis_extractor.analyseursyntaxique')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExampleExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_class', models.CharField(help_text="Classe/categorie de l'extraction attendue", max_length=100)),
                ('extraction_text', models.TextField(help_text='Texte exact attendu pour cette extraction')),
                ('order', models.PositiveIntegerField(default=0)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='hypostasis_extractor.analyseurexample')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Nom de l'attribut", max_length=100)),
                ('value', models.TextField(help_text="Valeur de l'attribut")),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='hypostasis_extractor.exampleextraction')),
            ],
        ),
        migrations.CreateModel(
            name='PromptPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du morceau de prompt', max_length=200)),
                ('role', models.CharField(choices=[('definition', 'Définition'), ('instruction', 'Instruction'), ('format', 'Format'), ('context', 'Contexte')], default='instruction', max_length=20)),
                ('content', models.TextField(help_text='Contenu du morceau de prompt')),
                ('order', models.PositiveIntegerField(default=0)),
                ('analyseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='hypostasis_extractor.analyseursyntaxique')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
