# Generated by Django 6.0 on 2026-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0003_analyseursyntaxique_analyseurexample_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extractionattribute',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='extractionattribute',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage / Display order"),
        ),
    ]
