# Generated by Django 6.0 on 2026-02-11 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dossier_alter_aimodel_model_choice_page_dossier'),
        ('hypostasis_extractor', '0004_extractionattribute_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseurTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model_display_name', models.CharField(help_text='Nom du modele fige au moment du test / Model name frozen at test time', max_length=200)),
                ('prompt_snapshot', models.TextField(help_text='Prompt complet concatene au moment du test / Full prompt at test time')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Termine'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('extractions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(blank=True, help_text='Modele LLM utilise pour ce test', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aimodel')),
                ('analyseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='hypostasis_extractor.analyseursyntaxique')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='hypostasis_extractor.analyseurexample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_class', models.CharField(max_length=200)),
                ('extraction_text', models.TextField()),
                ('start_pos', models.IntegerField(default=0)),
                ('end_pos', models.IntegerField(default=0)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='hypostasis_extractor.analyseurtestrun')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
