# Generated by Django 6.0 on 2026-02-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0005_analyseurtestrun_testrunextraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunextraction',
            name='annotation_note',
            field=models.TextField(blank=True, default='', help_text='Note humaine optionnelle / Optional human note'),
        ),
        migrations.AddField(
            model_name='testrunextraction',
            name='human_annotation',
            field=models.CharField(blank=True, choices=[('validated', 'Validee (ajoutee aux attendus)'), ('rejected', 'Inappropriee')], help_text='Annotation humaine : validee ou inappropriee / Human annotation: validated or rejected', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='testrunextraction',
            name='promoted_to_extraction',
            field=models.ForeignKey(blank=True, help_text='ExampleExtraction creee si validee / ExampleExtraction created if validated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from', to='hypostasis_extractor.exampleextraction'),
        ),
    ]
