# Generated by Django 6.0 on 2026-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0006_testrunextraction_annotation_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedentity',
            name='extraction_class',
            field=models.CharField(blank=True, default='', help_text="Classe/categorie de l'entite extraite", max_length=100),
        ),
    ]
