# Generated by Django 6.0 on 2026-02-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0007_alter_extractedentity_extraction_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(help_text="Prenom de l'auteur du commentaire / Author first name", max_length=100)),
                ('commentaire', models.TextField(help_text='Texte du commentaire / Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(help_text='Entite commentee / Commented entity', on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='hypostasis_extractor.extractedentity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
