# Generated by Django 6.0 on 2026-02-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0008_commentaireextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnairePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du prompt questionnaire', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('inclure_extractions', models.BooleanField(default=False, help_text='Injecter les extractions dans le contexte du prompt / Inject extractions into prompt context')),
                ('inclure_texte_original', models.BooleanField(default=False, help_text='Injecter le texte original dans le contexte du prompt / Inject original text into prompt context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnairePromptPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du morceau de prompt', max_length=200)),
                ('role', models.CharField(choices=[('definition', 'Définition'), ('instruction', 'Instruction'), ('format', 'Format'), ('context', 'Contexte')], default='instruction', max_length=20)),
                ('content', models.TextField(help_text='Contenu du morceau de prompt')),
                ('order', models.PositiveIntegerField(default=0)),
                ('questionnaire_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='hypostasis_extractor.questionnaireprompt')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
