# Generated by Django 6.0 on 2026-02-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0009_questionnaireprompt_questionnairepromptpiece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairepromptpiece',
            name='questionnaire_prompt',
        ),
        migrations.AddField(
            model_name='analyseursyntaxique',
            name='inclure_extractions',
            field=models.BooleanField(default=False, help_text='Injecter les extractions dans le contexte du prompt / Inject extractions into prompt context'),
        ),
        migrations.AddField(
            model_name='analyseursyntaxique',
            name='inclure_texte_original',
            field=models.BooleanField(default=False, help_text='Injecter le texte original dans le contexte du prompt / Inject original text into prompt context'),
        ),
        migrations.AddField(
            model_name='analyseursyntaxique',
            name='type_analyseur',
            field=models.CharField(choices=[('analyser', 'Analyser'), ('reformulater', 'Reformulater'), ('restituer', 'Restituer')], default='analyser', help_text="Type d'analyseur : analyser, reformulater ou restituer", max_length=20),
        ),
        migrations.DeleteModel(
            name='QuestionnairePrompt',
        ),
        migrations.DeleteModel(
            name='QuestionnairePromptPiece',
        ),
    ]
