# Generated by Django 6.0 on 2026-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0010_remove_questionnairepromptpiece_questionnaire_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseursyntaxique',
            name='type_analyseur',
            field=models.CharField(choices=[('analyser', 'Analyser'), ('reformuler', 'Reformuler'), ('restituer', 'Restituer')], default='analyser', help_text="Type d'analyseur : analyser, reformuler ou restituer", max_length=20),
        ),
    ]
