# Generated by Django 6.0 on 2026-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0011_alter_analyseursyntaxique_type_analyseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='est_reformulation',
            field=models.BooleanField(default=False, help_text='True si ce job est une reformulation (pas une extraction classique)'),
        ),
    ]
