# Generated by Django 6.0 on 2026-02-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0012_extractionjob_est_reformulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='reformulation_en_cours',
            field=models.BooleanField(default=False, help_text='True si une reformulation est en cours / True if reformulation is in progress'),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='reformule_par',
            field=models.CharField(blank=True, default='', help_text="Nom de l'analyseur qui a reformule / Name of the reformulating analyzer", max_length=200),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='texte_reformule',
            field=models.TextField(blank=True, default='', help_text='Texte reformule par un analyseur / Reformulated text by an analyzer'),
        ),
    ]
