# Generated by Django 6.0 on 2026-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0013_extractedentity_reformulation_en_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='reformulation_erreur',
            field=models.TextField(blank=True, default='', help_text="Message d'erreur de la derniere reformulation / Last reformulation error message"),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='reformulation_lancee_a',
            field=models.DateTimeField(blank=True, help_text='Timestamp du lancement de la reformulation (pour timeout) / Reformulation start timestamp (for timeout)', null=True),
        ),
    ]
