# Generated by Django 6.0 on 2026-02-17 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_page_parent_page_page_version_label_and_more'),
        ('hypostasis_extractor', '0014_extractedentity_reformulation_erreur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='restitution_date',
            field=models.DateTimeField(blank=True, help_text='Date de la restitution / Restitution date', null=True),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='restitution_page',
            field=models.ForeignKey(blank=True, help_text='Page version creee par restitution de ce debat / Page version created by restituting this debate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restitutions_source', to='core.page'),
        ),
    ]
