# Generated by Django 6.0 on 2026-02-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0015_extractedentity_restitution_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='restitution_texte',
            field=models.TextField(blank=True, default='', help_text='Texte de la restitution du debat / Debate restitution text'),
        ),
    ]
