# Generated by Django 6.0 on 2026-02-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0016_extractedentity_restitution_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='restitution_ia_en_cours',
            field=models.BooleanField(default=False, help_text='True si une restitution IA est en cours / True if AI restitution is in progress'),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='restitution_ia_erreur',
            field=models.TextField(blank=True, default='', help_text="Message d'erreur de la derniere restitution IA / Last AI restitution error message"),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='restitution_ia_lancee_a',
            field=models.DateTimeField(blank=True, help_text='Timestamp du lancement de la restitution IA (pour timeout) / AI restitution start timestamp (for timeout)', null=True),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='texte_restitution_ia',
            field=models.TextField(blank=True, default='', help_text="Texte de restitution genere par l'IA / AI-generated restitution text"),
        ),
    ]
