# Generated by Django 6.0.2 on 2026-03-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0017_extractedentity_restitution_ia_en_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='masquee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractedentity',
            name='statut_debat',
            field=models.CharField(choices=[('consensuel', 'Consensuel'), ('discutable', 'Discutable'), ('discute', 'Discuté'), ('controverse', 'Controversé')], default='discutable', max_length=20),
        ),
    ]
