# Generated by Django 6.0.2 on 2026-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0018_extractedentity_masquee_extractedentity_statut_debat'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
