# Generated by Django 6.0.2 on 2026-03-18 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0021_refactoring_statuts_debat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedentity',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant cree cette extraction manuellement / User who manually created this extraction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions_creees', to=settings.AUTH_USER_MODEL),
        ),
    ]
