# Generated by Django 6.0.2 on 2026-03-18 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0022_extractedentity_cree_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionjob',
            name='cout_reel_euros',
            field=models.FloatField(blank=True, help_text='Cout reel en euros / Real cost in euros', null=True),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='tokens_input_reels',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre de tokens d'entree reels / Real input token count", null=True),
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='tokens_output_reels',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de tokens de sortie reels / Real output token count', null=True),
        ),
        migrations.CreateModel(
            name='AnalyseurVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Numero de version auto-incremente / Auto-incremented version number')),
                ('snapshot', models.JSONField(help_text='Snapshot JSON complet (pieces, exemples, extractions, attributs) / Full JSON snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description_modification', models.CharField(blank=True, help_text='Description de la modification / Modification description', max_length=500)),
                ('analyseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hypostasis_extractor.analyseursyntaxique')),
                ('modified_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant effectue la modification / User who made the modification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyseur_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('analyseur', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='extractionjob',
            name='analyseur_version',
            field=models.ForeignKey(blank=True, help_text="Version de l'analyseur au moment de l'extraction / Analyzer version at extraction time", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to='hypostasis_extractor.analyseurversion'),
        ),
    ]
