# Generated by Django 6.0.2 on 2026-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0024_normalize_entity_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyseursyntaxique',
            name='type_analyseur',
            field=models.CharField(choices=[('analyser', 'Analyser'), ('reformuler', 'Reformuler'), ('restituer', 'Restituer'), ('synthetiser', 'Synthétiser')], default='analyser', help_text="Type d'analyseur : analyser, reformuler ou restituer", max_length=20),
        ),
    ]
