# Generated by Django 6.0.2 on 2026-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0025_alter_analyseursyntaxique_type_analyseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseursyntaxique',
            name='est_par_defaut',
            field=models.BooleanField(default=False, help_text='Marquer cet analyseur comme defaut pour son type. Cocher ici decoche automatiquement les autres analyseurs du meme type.'),
        ),
    ]
