# Generated by Django 6.0.2 on 2026-05-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0027_extractionjob_notification_lue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedentity',
            name='reformulation_en_cours',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='reformulation_erreur',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='reformulation_lancee_a',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='reformule_par',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='restitution_date',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='restitution_ia_en_cours',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='restitution_ia_erreur',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='restitution_ia_lancee_a',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='restitution_page',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='restitution_texte',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='texte_reformule',
        ),
        migrations.RemoveField(
            model_name='extractedentity',
            name='texte_restitution_ia',
        ),
        migrations.RemoveField(
            model_name='extractionjob',
            name='est_reformulation',
        ),
        migrations.AlterField(
            model_name='analyseursyntaxique',
            name='type_analyseur',
            field=models.CharField(choices=[('analyser', 'Analyser'), ('synthetiser', 'Synthétiser')], default='analyser', help_text="Type d'analyseur : analyser ou synthetiser / Analyzer type: analyser or synthetiser", max_length=20),
        ),
    ]
