# Generated by Django 6.0.2 on 2026-05-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0029_a8_recalcul_statuts_fusion_non_pertinent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedentity',
            name='statut_debat',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('commente', 'Commenté')], default='nouveau', help_text="Statut auto-derive de l'existence de commentaires. Mis a jour par signal Django, jamais set manuellement. / Status auto-derived from comment existence. Updated by Django signal, never set manually.", max_length=20),
        ),
    ]
