# Generated by Django 6.0.2 on 2026-08-05 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_elementdocument_elementoperation'),
        ('hypostasis_extractor', '0030_a8_alter_statut_debat_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncrageExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_dans_extraction', models.PositiveSmallIntegerField(help_text='0 pour la premiere portion (la plus a gauche dans le document), 1 pour la suivante, etc.')),
                ('debut_dans_element', models.PositiveIntegerField(help_text="Position de debut DANS LE TEXTE DE L'ELEMENT, jamais dans le texte global de la page / Start position within the ELEMENT text")),
                ('fin_dans_element', models.PositiveIntegerField(help_text="Position de fin DANS LE TEXTE DE L'ELEMENT / End position within the ELEMENT text")),
                ('etat_ancrage', models.CharField(choices=[('exacte', 'Exacte — position calculee au premier ancrage'), ('retrouvee', 'Retrouvée — repositionnee apres une edition'), ('detachee', 'Détachée — le passage source a change')], default='exacte', help_text='Resultat du dernier calcul de position / Result of the last positioning pass', max_length=16)),
                ('element', models.ForeignKey(help_text='Element qui porte cette portion / Element carrying this portion', on_delete=django.db.models.deletion.PROTECT, related_name='portions_d_extractions', to='core.elementdocument')),
                ('extraction', models.ForeignKey(help_text='Extraction dont ceci est une portion / Extraction this is a portion of', on_delete=django.db.models.deletion.CASCADE, related_name='ancrages', to='hypostasis_extractor.extractedentity')),
            ],
            options={
                'verbose_name': "Ancrage d'extraction",
                'verbose_name_plural': "Ancrages d'extraction",
                'ordering': ['extraction', 'ordre_dans_extraction'],
                'constraints': [models.UniqueConstraint(fields=('extraction', 'ordre_dans_extraction'), name='unicite_ordre_dans_l_extraction')],
            },
        ),
    ]
