# Generated by Django 6.0.2 on 2026-08-05 12:08

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_elementdocument_unicite_ordre_dans_la_page_and_more'),
        ('hypostasis_extractor', '0031_ancrageextraction'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ancrageextraction',
            name='unicite_ordre_dans_l_extraction',
        ),
        migrations.AddConstraint(
            model_name='ancrageextraction',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('extraction', 'ordre_dans_extraction'), name='unicite_ordre_dans_l_extraction'),
        ),
    ]
