# Generated by Django 6.0.2 on 2026-08-05 16:31

from django.db import migrations, models


def convertir_les_anciens_etats_en_ancree(apps, schema_editor):
    """
    Convertit 'exacte' et 'retrouvee' en 'ancree'.
    / Converts 'exacte' and 'retrouvee' into 'ancree'.

    Les deux anciens etats se comportaient exactement pareil : ni le
    regime d'edition, ni l'affichage, ni le calcul de l'etat de l'element
    ne les distinguaient. Seul DETACHEE comptait. Les fusionner ne perd
    donc aucune information utilisee.
    / Both old states behaved identically; only DETACHEE ever mattered.
    """
    AncrageExtraction = apps.get_model("hypostasis_extractor", "AncrageExtraction")
    nombre_converti = AncrageExtraction.objects.filter(
        etat_ancrage__in=["exacte", "retrouvee"],
    ).update(etat_ancrage="ancree")
    if nombre_converti:
        print(f"  -> {nombre_converti} portion(s) passee(s) a 'ancree'")


def revenir_a_exacte(apps, schema_editor):
    """
    Retour arriere : tout ce qui est ancre redevient 'exacte'.
    / Rollback: everything anchored goes back to 'exacte'.

    On ne peut pas distinguer ce qui etait 'exacte' de ce qui etait
    'retrouvee' : l'information a ete fusionnee. On choisit 'exacte',
    qui etait la valeur par defaut.
    / The distinction is gone; we pick the former default.
    """
    AncrageExtraction = apps.get_model("hypostasis_extractor", "AncrageExtraction")
    AncrageExtraction.objects.filter(etat_ancrage="ancree").update(
        etat_ancrage="exacte",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0032_remove_ancrageextraction_unicite_ordre_dans_l_extraction_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convertir_les_anciens_etats_en_ancree,
            reverse_code=revenir_a_exacte,
        ),
        migrations.AlterField(
            model_name='ancrageextraction',
            name='etat_ancrage',
            field=models.CharField(choices=[('ancree', 'Ancrée — le passage source est localisé'), ('detachee', 'Détachée — le passage source a changé')], default='ancree', help_text='Resultat du dernier calcul de position / Result of the last positioning pass', max_length=16),
        ),
    ]
