# Generated by Django 6.0.2 on 2026-08-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0033_simplification_element_parent_et_etats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionjob',
            name='notification_lue',
            field=models.BooleanField(default=False, help_text='Notification de fin lue par le proprietaire / End-of-task notification read by the owner. MORT pour la decision depuis la correction 1 (11 aout 2026) : voir core.models.NotificationTacheLue, qui porte le drapeau PAR DESTINATAIRE. Champ laisse en base mais plus ecrit ni lu.'),
        ),
    ]
