# Generated by Django 6.0.2 on 2026-08-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0035_prompt_de_synthese_sans_statuts_abolis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedentity',
            name='end_char',
            field=models.PositiveIntegerField(help_text="Offset de fin relatif au chunk analyse (herite de l'ancien moteur). L'ancrage reel est AncrageExtraction."),
        ),
        migrations.AlterField(
            model_name='extractedentity',
            name='start_char',
            field=models.PositiveIntegerField(help_text="Offset de debut relatif au chunk analyse (herite de l'ancien moteur). L'ancrage reel est AncrageExtraction."),
        ),
    ]
