# Generated by Django 6.0.2 on 2026-09-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_les_cles_de_provenance_audio'),
        ('hypostasis_extractor', '0036_alter_extractedentity_end_char_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceDeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(choices=[('analyse', "Analyse d'une note"), ('synthese_note', "Synthèse d'une note"), ('wiki', 'Article de wiki'), ('synthese_dirigee', 'Synthèse dirigée de carnet'), ('maj_wiki', "Mise à jour d'un wiki")], help_text='Le geste qui a envoyé ce prompt / The sending gesture', max_length=30)),
                ('empreinte', models.CharField(db_index=True, help_text='SHA-256 du prompt assemblé / SHA-256 of the prompt', max_length=64)),
                ('longueur', models.PositiveIntegerField(help_text='Longueur du prompt assemblé, en caractères / Assembled prompt length, in characters')),
                ('extractions_montrees', models.JSONField(blank=True, default=list, help_text="Les identifiants d'extractions montrés au modèle, triés / The extraction ids shown to the model, sorted")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('analyseur', models.ForeignKey(blank=True, help_text="L'analyseur dont le préambule a servi / The analyzer used", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenances', to='hypostasis_extractor.analyseursyntaxique')),
                ('analyseur_version', models.ForeignKey(blank=True, help_text="La version de cet analyseur au moment de l'envoi / That analyzer's version at send time", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenances', to='hypostasis_extractor.analyseurversion')),
                ('job', models.ForeignKey(blank=True, help_text="Le job de la demande, s'il y en a un / The job, if any", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenances', to='hypostasis_extractor.extractionjob')),
                ('modele', models.ForeignKey(blank=True, help_text='Le modèle qui a reçu ce prompt / The model that got it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenances', to='core.aimodel')),
                ('tour_de_wiki', models.ForeignKey(blank=True, help_text='Le tour de wiki que cette production a écrit / The wiki round this production wrote', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenances', to='core.tourdewiki')),
            ],
            options={
                'verbose_name': 'Provenance de production',
                'verbose_name_plural': 'Provenances de production',
                'ordering': ['-cree_le', '-pk'],
            },
        ),
    ]
