# Generated by Django 6.0.2 on 2026-09-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0038_le_type_rediger_un_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptpiece',
            name='name',
        ),
    ]
