# Generated by Django 6.0.2 on 2026-09-01 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0039_le_morceau_de_prompt_n_a_pas_de_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseursyntaxique',
            name='inclure_extractions',
        ),
        migrations.RemoveField(
            model_name='analyseursyntaxique',
            name='inclure_texte_original',
        ),
    ]
