# Generated by Django 6.0.2 on 2026-09-01 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models




NOMS_DES_ANALYSEURS_D_ORIGINE = (
    "Hypostasia",
    "Synthèse délibérative",
    "Rédacteur d'article",
)


def marquer_les_analyseurs_d_origine(apps, schema_editor):
    """
    Estampille les analyseurs que l'installation a posés.
    / Stamps the analyzers the installation created.

    LE CHAMP NAIT A `False` : sans cette passe, les trois prompts sur
    lesquels tout le site retombe seraient modifiables par n'importe
    quel compte, et la garde neuve ne protegerait rien.
    / The field defaults to False: without this pass the guard protects
    nothing.

    LE NOM SERT ICI, ET SEULEMENT ICI. Il identifie ce que
    l'installation a pose a ce jour ; ensuite, c'est le CHAMP qui fait
    foi — un renommage ne deverrouille donc rien.
    / The name identifies them once; the field rules afterwards.
    """
    AnalyseurSyntaxique = apps.get_model(
        "hypostasis_extractor", "AnalyseurSyntaxique",
    )
    marques = AnalyseurSyntaxique.objects.filter(
        name__in=NOMS_DES_ANALYSEURS_D_ORIGINE,
    ).update(est_d_origine=True)
    print(
        f"[migration 0041] {marques} analyseur(s) estampillé(s) "
        f"« d'origine » : seul un superutilisateur pourra les modifier."
    )


def desestampiller(apps, schema_editor):
    """Le retrait rend tout le monde ordinaire. / The reverse unstamps."""
    AnalyseurSyntaxique = apps.get_model(
        "hypostasis_extractor", "AnalyseurSyntaxique",
    )
    AnalyseurSyntaxique.objects.update(est_d_origine=False)


class Migration(migrations.Migration):

    dependencies = [
        ('hypostasis_extractor', '0040_les_deux_bascules_d_injection_disparaissent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyseursyntaxique',
            name='est_d_origine',
            field=models.BooleanField(default=False, help_text="Analyseur posé par l'installation. Seul un superutilisateur peut le modifier : c'est le prompt sur lequel tout le site retombe, et une modification malheureuse s'y propage à toutes les productions."),
        ),
        migrations.CreateModel(
            name='PreferenceD_analyseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_analyseur', models.CharField(choices=[('analyser', 'Analyser'), ('synthetiser', 'Synthétiser'), ('rediger_un_article', 'Rédiger un article')], help_text="Le geste auquel cette préférence s'applique / The gesture this preference applies to", max_length=20)),
                ('posee_le', models.DateTimeField(auto_now=True)),
                ('analyseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferee_par', to='hypostasis_extractor.analyseursyntaxique')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_d_analyseur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Préférence d'analyseur",
                'verbose_name_plural': "Préférences d'analyseur",
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'type_analyseur'), name='une_preference_par_utilisateur_et_par_type')],
            },
        ),
            migrations.RunPython(
            marquer_les_analyseurs_d_origine,
            reverse_code=desestampiller,
        ),
    ]
