"""
Django settings for hypostasia project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Cle secrete : depuis .env en prod, fallback insecure pour le dev local
# / Secret key: from .env in prod, insecure fallback for local dev
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-k$6h%42un)h996fsk35s0*mu-^89nl=&6&w@m#e9d_$m#gepuv",
)

# Mode debug : depuis .env, True par defaut en dev local
# / Debug mode: from .env, True by default for local dev
DEBUG = os.environ.get("DEBUG", "true").lower() in ("true", "1", "yes")

# ALLOWED_HOSTS : localhost en dev + domaine de production depuis .env
# Pas de https:// — Django attend juste le nom de domaine nu
# / ALLOWED_HOSTS: localhost in dev + production domain from .env
# / No https:// — Django expects bare domain names only
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]
if os.environ.get("DOMAIN"):
    ALLOWED_HOSTS.append(os.environ["DOMAIN"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_htmx',
    'corsheaders',
    'solo',
    'django_celery_results',
    'core',
    'hypostasis_extractor',
    'front',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hypostasia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hypostasia.wsgi.application'


# Database — PostgreSQL partout (dev, prod, boitier offline)
# / Database — PostgreSQL everywhere (dev, prod, offline box)
# Defaults = valeurs du docker-compose.dev.yml → dev marche sans .env
# / Defaults = docker-compose.dev.yml values → dev works without .env

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "hypostasia"),
        "USER": os.environ.get("POSTGRES_USER", "hypostasia"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "hypostasia_dev"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# CORS & CSRF Settings for Extension
# Headers CORS autorises — inclut Authorization pour le token API de l'extension
# / Allowed CORS headers — includes Authorization for extension API token
CORS_ALLOW_HEADERS = [
    "accept", "content-type", "authorization",
    "x-csrftoken", "x-requested-with",
]

CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:8123",
    "http://localhost:8123",
    "http://0.0.0.0:8123",
    "chrome-extension://lmflifaokphpaknpdnmdmhdiaeiieomd",
]

# Ajoute le domaine de production depuis la variable d'environnement DOMAIN
# / Add production domain from the DOMAIN environment variable
_domaine_production = os.environ.get("DOMAIN")
if _domaine_production:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_domaine_production}")
    CSRF_TRUSTED_ORIGINS.append(f"http://{_domaine_production}")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (fichiers source uploades)
# / Media files (uploaded source files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# =============================================================================
# Celery — Redis partout (dev, prod, boitier offline)
# / Celery — Redis everywhere (dev, prod, offline box)
# =============================================================================

CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://localhost:6379/0")

CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes max par tache / 30 min max per task


# =============================================================================
# Repertoire temporaire pour les fichiers audio en attente de transcription
# / Temporary directory for audio files awaiting transcription
# =============================================================================

# =============================================================================
# Auth — URLs de redirection pour login/logout
# / Auth — Redirect URLs for login/logout
# =============================================================================

LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/auth/login/"


# =============================================================================
# Email — console backend en dev, SMTP via env vars en prod
# / Email — console backend in dev, SMTP via env vars in prod
# =============================================================================

EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@hypostasia.org")
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8123")


AUDIO_TEMP_DIR = BASE_DIR / "tmp" / "audio"
AUDIO_TEMP_DIR.mkdir(parents=True, exist_ok=True)


# =============================================================================
# Logging — verbeux en console + fichier parsable par Claude Code
# / Logging — verbose in console + file parsable by Claude Code
# =============================================================================

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} — {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {name} — {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'DEBUG',
        },
        'file_extractor': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'extractor.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'file_core': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'core.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        'file_django': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'django.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 3,
            'formatter': 'verbose',
            'level': 'INFO',
        },
    },
    'loggers': {
        # Logger pour l'app hypostasis_extractor (views, services, etc.)
        'hypostasis_extractor': {
            'handlers': ['console', 'file_extractor'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger pour l'app core
        'core': {
            'handlers': ['console', 'file_core'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Logger pour l'app front
        'front': {
            'handlers': ['console', 'file_core'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Django interne (requetes, SQL, etc.)
        'django': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file_django'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
